version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:ft_transcendence 
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - frontend_backend
    env_file:
      - .env
    restart: always

  frontend: 
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_URL_SOCKET: ${VITE_API_URL_SOCKET}
        VITE_API_HOST: ${VITE_API_HOST}
    image: frontend:ft_transcendence 
    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules

    networks:
      - frontend_backend
    restart: always

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    image: nginx:ft_transcendence 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
      - grafana
      - prometheus
      - alertmanager
    networks:
      - frontend_backend
      - monitoring

  prometheus:
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    image: prometheus:ft_transcendence 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries' 
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=https://${DOMAINE_NAME}/prometheus' 
    networks:
      - monitoring
      - frontend_backend
    restart: always

  grafana:
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
    image: grafana:ft_transcendence 
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://${DOMAINE_NAME}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    env_file:
      - .env
    networks:
      - monitoring

  alertmanager:
    build:
      context: ./monitoring/Alertmanager
      dockerfile: Dockerfile
    image: alertmanager:ft_transcendence 
    volumes:
      - alertmanager_data:/alertmanager
    environment:
      - EXTERNAL_URL=https://${DOMAINE_NAME}/alertmanager
    env_file:
      - .env
    networks:
      - monitoring
      - frontend_backend

  nginx_exporter:
    build:
      context: ./monitoring/nginx_exporter
      dockerfile: Dockerfile
    image: nginx_exporter:ft_transcendence 
    depends_on:
      - nginx
    ports:
      - "9113:9113"
    networks:
      - monitoring
      - frontend_backend

  node_exporter:
    build:
      context: ./monitoring/node_exporter
      dockerfile: Dockerfile
    image: node_exporter:ft_transcendence 
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
  frontend_backend:

volumes:
  backend_node_modules:
  frontend_node_modules:
  alertmanager_data:
