export const Game = {
    en: {
      game_center: "GAME CENTER",
      select_favorite_game: "Select your favorite game and start playing",
      choose_your_game: "Choose your game and start playing",
      classic: "CLASSIC",
      strategy: "STRATEGY",
      play_now: "Play Now",
      single_player: "Single Player",
      multiplayer: "Multiplayer",
      tournaments: "Tournaments",
  
      ping_pong_title: "Ping Pong",
      ping_pong_desc: "Classic table tennis action with multiple game modes",
  
      tic_tac_toe_title: "Tic Tac Toe",
      tic_tac_toe_desc: "Strategic grid-based game for quick thinking battles",
      tic_local_title: "Local",
      tic_local_desc: "Play against a friend on the same device",
      tic_local_btn: "Play Local",
      tic_online_title: "Online",
      tic_online_desc: "Challenge players worldwide online",
      tic_online_btn: "Start Battle",
      tic_footer_select: "Select your game mode",
      tic_footer_local: "Local Play",
      tic_footer_online: "Online Battle",
      tic_footer_strategy: "Strategy Game",
      play_again: "Play Again",
      new_game: "New Game",
      welcome: "Welcom !",
      enter_ur_name: "Enter your name:",
      choose_ur_symbole: "Choose your symbol:",
      play_against: "You'll play against",
      winner: "Winner!",
      wins: "wins! 🎉",
      next_player: "Next player:",
      its_draw: "It's a draw!",
      you_win: "You Win! 🎉",
      you_lost: "You Lost!",
      go_back: "Go Back",
      you_win_opponent_timed_out: "You Win! Opponent Timed Out ⏳",
      you_lost_times_up: "You Lost! Time's Up ⏳",
      you_win_opp_disconnected: "You Win! Opponent Disconnected",
      leave_game: "Leave Game",
      cnx_lost: "Connection Lost",
      finding_match: "Finding Match",
      connecting_u_with_an_opp: "Connecting you with an opponent...",
      you: "You",
      opponant: "Opponent",
      search_for_players: "Searching for players",
      cancel_search: "Cancel Search",
      text: "You'll be automatically assigned X or O when the game starts. The first player to join gets X and goes first!",
      out_of_time: "ran out of time ⏳",
      left: "left",
      ur_turn: "Your turn",
      s_turn: "'s turn",
      join_game: "Join Game",
      pong: "Pong",
      pong_choose: "Choose your gaming experience and challenge yourself",
      competitive: "COMPETITIVE",
      join_tournanemt: "Join Tournament",
      compete: "Compete in structured battles and climb the leaderboard",
      local: "Local",
      classic_couch: "Classic couch gaming with friends on the same device",
      play_local: "Play Local",
      online: "Online",
      start_battle: "Start Battle",
      select_ur_prefered: "Select your preferred game mode",
      local_and_remote: "Local & Remote",
      tournament: "Tournaments",
      cros_platforme: "Cross-Platform",
      challenge: "Challenge players worldwide in real-time battles",
      remote: "Remote",
      game_err: "Game Error",
      go_back_to_chat: "Go Back to Chat",
      palyer_left: "The Player Left The Game!",
      back_to_chat: "Back to Chat",
      get_ready: "Get Ready!",
      game_start_in: "Game starts in:",
      waiting_for_game: "Waiting for Game...",
      setting_up: "Setting up your Pong match",
      cancel: "Cancel",
      f_back_to_chat: "← Back to Chat",
      game_over: "Game Over!",
      left_player_win: "Left Player Wins!",
      right_player_win: "Right Player Wins!",
      start_game: "Start Game",
      rematch: "Rematch",
      another_game: "Another Game",
      match_found: "MATCH FOUND!",
      get_some_water: "Get some water while waiting for the other player",
      in_progress: "in_progress",
      playing: "playing",
      completed: "completed",
      finished: "finished",
      pending: "pending",
      awaiting_challenger: "Awaiting Challenger",
      loading_arena: "Loading Arena...",
      praeparing_stage: "Preparing the stage for battle.",
      error: "Error",
      go_home: "Go Home",
      trn_not_found: "Tournament Not Found",
      has_vanished: "This tournament has vanished into the aether.",
      an_elite: "An elite championship of skill and glory.",
      Players: "Players",
      battle_comm: "Battle Commencing",
      prepare_for_glory: "Prepare for glory!",
      champions: "Champion:",
      trn_ending_in: "Tournament ending in:",
      no_champion: "No champion was determined.",
      trn_master: "Tournament Master",
      start_trn: "Start Tournament",
      waiting_for: "Waiting for",
      more_players_to_join: "more players to join",
      delete_trn: "Delete Tournament",
      start_next_round: "Start Next Round",
      active: "Active",
      Eliminated: "Eliminated",
      awaitng_warr: "Awaiting Warrior",
      Round: "Round",
      matches: "matches",
      Completed: "Completed",
      Live: "Live",
      Pending:"Pending",
      winner_: "Winner:",
      score: "Score:",
      create_trn: "Create Tournament",
      name: "Name",
      max_players: "Max Players:",
      own_player: "Owner plays",
      creating: "Creating...",
      Create: "Create",
      TOURNAMENT : "TOURNAMENT",
      Elite_Competition : "Elite Competition",
      High_Stakes : "High Stakes",
      Connected_as : "Connected as",
      SECONDS : "SECONDS",
      prepare_for_tournament_p: "Prepare for an intense tournament match. Show your skills and claim victory!",
      Player_Eliminated : "Player Eliminated",
      opponent_left_p: "Your opponent has left the tournament. The match has been concluded.",
      Victory_Default : "Victory by Default",
      congrats_player_left : "Congratulations! You advance to the next round automatically.",
      Continue_Tournament_btn : "Continue Tournament",
      Failed_to_fetch_tournament : "Failed to fetch tournament",
      Empty_response_from_the_server : "Empty response from the server.",
      Unknown_error : "Unknown error",
      Error_leaving_tournament : "Error leaving tournament",
      User_not_loaded_yet : "User not loaded yet",
      You_are_already_in_this_tournament : "You are already in this tournament!",
      Tournament_is_full : "Tournament is full!",
      Tournament_already_started : "Tournament already started",
      Error_joining_tournament : "Error joining tournament",
      Tournament_Arena : "Tournament Arena",
      join_parag : "Join competitive tournaments and prove your skills",
      no_tourn : "No Tournaments Available",
      check_back_later_par : "Check back later for new tournaments",
      owner : "Owner",
      Joined : "Joined",
      Full : "Full",
      Join_Tournament : "Join Tournament",
      Leave : "Leave",
      View_Board : "View Board",
      waiting : "waiting",
      Already_started : "Already started",
      Already_in_another_tournament : "Already in another tournament",
      Cannot_join : "Cannot join",
      Pong_Tournaments : "Pong Tournaments",
      Create_a_Tournament : "Create a Tournament",
      Join_a_Tournament : "Join a Tournament",
      Choose_your_gaming_experience_and_challenge_yourself:
      "Choose your gaming experience and challenge yourself",
      touch_right: "Touch left/right sides to move paddles or use W/S and ↑/↓",
      ws: "W/S and ↑/↓ to move",
    },
  
    fr: {
      game_center: "CENTRE DE JEU",
      select_favorite_game: "Sélectionnez votre jeu préféré et commencez à jouer",
      choose_your_game: "Choisissez votre jeu et commencez à jouer",
      classic: "CLASSIQUE",
      strategy: "STRATÉGIE",
      play_now: "Jouer Maintenant",
      single_player: "Solo",
      multiplayer: "Multijoueur",
      tournaments: "Tournois",
  
      ping_pong_title: "Ping Pong",
      ping_pong_desc: "Action classique de tennis de table avec plusieurs modes de jeu",
  
      tic_tac_toe_title: "Morpion",
      tic_tac_toe_desc: "Jeu de stratégie sur grille pour des duels rapides",
      tic_local_title: "Local",
      tic_local_desc: "Jouez contre un ami sur le même appareil",
      tic_local_btn: "Jouer en Local",
      tic_online_title: "En Ligne",
      tic_online_desc: "Défiez des joueurs du monde entier en ligne",
      tic_online_btn: "Commencer le Duel",
      tic_footer_select: "Sélectionnez votre mode de jeu",
      tic_footer_local: "Jeu Local",
      tic_footer_online: "Duel en Ligne",
      tic_footer_strategy: "Jeu de Stratégie",
      play_again: "Rejouer",
      new_game: "Nouvelle Partie",
      welcome: "Bienvenue !",
      enter_ur_name: "Entrez votre nom :",
      choose_ur_symbole: "Choisissez votre symbole :",
      play_against: "Vous jouerez contre",
      winner: "Gagnant !",
      wins: "gagne ! 🎉",
      next_player: "Prochain joueur :",
      its_draw: "Match nul !",
      you_win: "Vous avez gagné ! 🎉",
      you_lost: "Vous avez perdu !",
      go_back: "Retour",
      you_win_opponent_timed_out: "Vous avez gagné ! L’adversaire a dépassé le temps ⏳",
      you_lost_times_up: "Vous avez perdu ! Temps écoulé ⏳",
      you_win_opp_disconnected: "Vous avez gagné ! L’adversaire s’est déconnecté",
      leave_game: "Quitter la Partie",
      cnx_lost: "Connexion Perdue",
      finding_match: "Recherche d’une partie",
      connecting_u_with_an_opp: "Connexion à un adversaire...",
      you: "Vous",
      opponant: "Adversaire",
      search_for_players: "Recherche de joueurs",
      cancel_search: "Annuler la Recherche",
      text: "Vous recevrez automatiquement X ou O au début du jeu. Le premier joueur à rejoindre reçoit X et commence !",
      out_of_time: "a dépassé le temps ⏳",
      left: "a quitté",
      ur_turn: "À votre tour",
      s_turn: "joue",
      join_game: "Rejoindre la Partie",
    },
  
    es: {
      game_center: "CENTRO DE JUEGOS",
      select_favorite_game: "Selecciona tu juego favorito y comienza a jugar",
      choose_your_game: "Elige tu juego y empieza a jugar",
      classic: "CLÁSICO",
      strategy: "ESTRATEGIA",
      play_now: "Jugar Ahora",
      single_player: "Un Jugador",
      multiplayer: "Multijugador",
      tournaments: "Torneos",
  
      ping_pong_title: "Ping Pong",
      ping_pong_desc: "Acción clásica de tenis de mesa con varios modos de juego",
  
      tic_tac_toe_title: "Tres en Raya",
      tic_tac_toe_desc: "Juego de estrategia en cuadrícula para batallas rápidas",
      tic_local_title: "Local",
      tic_local_desc: "Juega contra un amigo en el mismo dispositivo",
      tic_local_btn: "Jugar Local",
      tic_online_title: "En Línea",
      tic_online_desc: "Desafía a jugadores de todo el mundo en línea",
      tic_online_btn: "Comenzar Batalla",
      tic_footer_select: "Selecciona tu modo de juego",
      tic_footer_local: "Juego Local",
      tic_footer_online: "Batalla en Línea",
      tic_footer_strategy: "Juego de Estrategia",
      play_again: "Jugar de Nuevo",
      new_game: "Nuevo Juego",
      welcome: "¡Bienvenido!",
      enter_ur_name: "Introduce tu nombre:",
      choose_ur_symbole: "Elige tu símbolo:",
      play_against: "Jugarás contra",
      winner: "¡Ganador!",
      wins: "¡gana! 🎉",
      next_player: "Siguiente jugador:",
      its_draw: "¡Empate!",
      you_win: "¡Has ganado! 🎉",
      you_lost: "¡Has perdido!",
      go_back: "Volver",
      you_win_opponent_timed_out: "¡Has ganado! El oponente se quedó sin tiempo ⏳",
      you_lost_times_up: "¡Has perdido! Se acabó el tiempo ⏳",
      you_win_opp_disconnected: "¡Has ganado! El oponente se desconectó",
      leave_game: "Salir del Juego",
      cnx_lost: "Conexión Perdida",
      finding_match: "Buscando Partida",
      connecting_u_with_an_opp: "Conectando con un oponente...",
      you: "Tú",
      opponant: "Oponente",
      search_for_players: "Buscando jugadores",
      cancel_search: "Cancelar Búsqueda",
      text: "Se te asignará automáticamente X u O al comenzar. ¡El primer jugador en unirse obtiene X y empieza!",
      out_of_time: "se quedó sin tiempo ⏳",
      left: "salió",
      ur_turn: "Tu turno",
      s_turn: "le toca a",
      join_game: "Unirse al Juego",
    },
  };
  
  export default Game;