global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']




# global:
#   scrape_interval: 5s
#   evaluation_interval: 5s


# rule_files:
#   - "alert_rules.yml"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# scrape_configs:
#   - job_name: 'nginx-exporter'
#     static_configs:
#       - targets: ['nginx_exporter:9113']

#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node_exporter:9100']
